# Generated by Django 3.2.15 on 2022-09-10 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSV', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
            ],
        ),
    ]
